# Ioana A Mititean
# UWPCE Course 3 - Internet Programming in Python
# Django

"""
Initial migration file, generated by Django. Includes a Migration class that creates the Post
model.
"""

# Generated by Django 4.0 on 2021-12-17 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    """
    Migration class - specifies the operation to create the Post model.
    """

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("text", models.TextField(blank=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("published_date", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auth.user"
                    ),
                ),
            ],
        ),
    ]
