# Ioana A Mititean
# UWPCE Course 3 - Internet Programming in Python
# Django

"""
Migration file, generated by Django. Includes a Migration class that creates the Category model.
"""

# Generated by Django 4.0 on 2022-01-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    """
    Migration class - specifies the operation to create the Category model.
    """

    dependencies = [
        ("blogging", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                (
                    "posts",
                    models.ManyToManyField(
                        blank=True, related_name="categories", to="blogging.Post"
                    ),
                ),
            ],
        ),
    ]
